apiVersion: v1
kind: Service
metadata:
  name: tendermint-client
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9091"
spec:
  selector:
    app: tendermint-client
  ports:
    - port: 9091
      targetPort: 9091
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tendermint-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tendermint-client
  template:
    metadata:
      labels:
        app: tendermint-client
    spec:
      # affinity:
      #   podAntiAffinity:
      #     requiredDuringSchedulingIgnoredDuringExecution:
      #       - labelSelector:
      #           matchExpressions:
      #             - key: app
      #               operator: In
      #               values:
      #                 - libhotstuff-server
      #         topologyKey: kubernetes.io/hostname
      containers:
        - name: tendermint-client
          image: balajia/tm-load-test:latest
          imagePullPolicy: Always
          command:
            - "/bin/sh"
            - "-ecx"
            # The use of qualified `hostname -f` is crucial:
            # Other nodes aren't able to look up the unqualified hostname.
          args:
            - "echo -e \"\n\n# Tendermint Hosts\n\" >> /etc/hosts && curl ssrg:5060/ips >> /etc/hosts && cat /etc/hosts && /tendermint/tm-load-test -c 1 -T 10 -r 1000 -s 250 --broadcast-tx-method async --endpoints ws://node0:26657/websocket,ws://node1:26657/websocket"
          ports:
            - containerPort: 7000
          env:
            - name: HOSTMACHINE
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: REGION
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
      # No pre-stop hook is required, a SIGTERM plus some time is all that's
      # needed for graceful shutdown of a node.
      terminationGracePeriodSeconds: 5
      hostAliases:
        - ip: "198.82.148.41"
          hostnames:
            - "ssrg"
